### ISSUE TITLE
Js index error

### ISSUE THREAD

**Issue by azlux** [Johni0702/mumble-web#1]
TypeError: superCtor.prototype is not an object or null
  index.js:9869:23

Any idea of this error ?
(example here : http://mumble.crystalyx.net/web/)

**Comment by Johni0702** [comment]
No, I've never seen it before. It seems to be caused by a circular reference between Stream and Transform. Not sure why or how though.

What version of node/npm/webpack has this been build with?

**Comment by azlux** [comment]
$ nodejs -v
v6.9.4
$ npm -v
3.10.10

no idea how to have the webpack version.

**Comment by flussence** [comment]
Identical error here, I installed via git using a clean user account.
```
~/mumble-web $ node -v; npm -v; npm ls webpack
v7.5.0
4.1.2
mumble-web@0.0.1 /srv/mumbleweb/mumble-web
└── webpack@1.14.0
```

**Comment by azlux** [comment]
@Johni0702 So ? And what is yours versions ?
