### ISSUE TITLE
setup mumble-web with multiple virtual mumble servers

### ISSUE THREAD

**Issue by ferdinandhubbard981** [Johni0702/mumble-web#110]
Everything is working for a single mumble server. 
But if I want to have say 5 virtual servers running at different paths like https://localhost/server1 would redirect to server1 on it's own port. https://localhost/server2 would redirect to server2 running on it's own port. 
Do you need to use the proxy setup or is that only when 443 is already being used?
Or can you use the standalone setup and make this work?
Any help would be much appreciated.

**Comment by streaps** [comment]
I think you would need to run a separate websocket proxy for every virtual server. Maybe mumble-web-proxy could support a range or list of ports?

If you are using a http proxy (like nginx), there are several ways to do it. The important part is to proxy the websocket connection to the websocket proxy for the specific virtual server. E.g.:

https://example.com/?port=/server1
wss://example.com/server1 -> localhost:54738 -> localhost:64738

https://example.com/?port=/server2
wss://example.com/server2 -> localhost:54739 -> localhost:64739

https://example.com/?port=/server3
wss://example.com/server3 -> localhost:54740 -> localhost:64740

**Comment by ferdinandhubbard981** [comment]
Thanks, it works(I used nginx) and setup websockify (websockify --ssl-target 54739 localhost:64739) for each server

[nginx.txt](https://github.com/Johni0702/mumble-web/files/4623151/nginx.txt)

**Comment by ferdinandhubbard981** [comment]
Thanks, it works(I used nginx) and setup websockify (websockify --ssl-target 54739 localhost:64739) for each server
