### ISSUE TITLE
Sound does not work with webrtc

### ISSUE THREAD

**Issue by Gittenburg** [Johni0702/mumble-web#112]
I installed the webrtc version from Git (456a2fc) and [mumble-web-proxy](https://github.com/johni0702/mumble-web-proxy) also from Git (Johni0702/mumble-web-proxy@2a95f11). I configured NGINX like in the README.

With the web client nobody can hear anybody else (not even those using the native client). Talking also does not work (is also not received with the native client).

What appears to work:
* the input volume meter in the settings
* the talking indicators show if native clients are talking (but you cannot hear them)

Tested with:
* latest murmur on Debian (1.3.0)
* node v10.19.0
* Firefox 76 and Chromium 80.

In Firefox the console says `ICE failed, add a STUN server and see about:webrtc for more details` and `about:webrtc` says ICE State failed.

**Comment by Johni0702** [comment]
Does your mumble-web build work when using the demo mumble server?
Does the demo mumble-web build work when using your mumble server?

What does mumble-web-proxy output?
Does your server have more than one public IP, an active firewall, or is it behind NAT?

**Comment by Gittenburg** [comment]
My mumble-web instance works with the demo server.

The mumble-web demo instance does not work with my mumble server.

mumble-web-proxy output:

```
New connection from [::1]:47324
MSG Authenticate: username: "test123" password: "" opus: false webrtc: true
Local ice candidate: 1 1 UDP 2013266431 <server_local_ipv6_scope_link> 38584 typ host
Local ice candidate: 2 1 TCP 1015023871 <server_local_ipv6_scope_link> 0 typ host tcptype active
Local ice candidate: 3 1 TCP 1010829567 <server_local_ipv6_scope_link> 48057 typ host tcptype passive
Local ice candidate: 4 1 UDP 2013266430 <server_local_ipv6_scope_global> 33868 typ host
Local ice candidate: 5 1 TCP 1015022079 <server_local_ipv6_scope_global> 0 typ host tcptype active
Local ice candidate: 6 1 TCP 1010827775 <server_local_ipv6_scope_global> 38317 typ host tcptype passive
Local ice candidate: 7 1 UDP 2013266429 <server_public_ipv6_scope_link> 35574 typ host
Local ice candidate: 8 1 TCP 1015023870 <server_public_ipv6_scope_link> 0 typ host tcptype active
Local ice candidate: 9 1 TCP 1010829566 <server_public_ipv6_scope_link> 56587 typ host tcptype passive
Local ice candidate: 10 1 UDP 2013266428 <server_public_ipv6_scope_global> 53743 typ host
Local ice candidate: 11 1 TCP 1015022591 <server_public_ipv6_scope_global> 0 typ host tcptype active
Local ice candidate: 12 1 TCP 1010828287 <server_public_ipv6_scope_global> 56471 typ host tcptype passive
Local ice candidate: 13 1 UDP 2013266427 <server_local_ipv4> 47105 typ host
Local ice candidate: 14 1 TCP 1015022847 <server_local_ipv4> 0 typ host tcptype active
Local ice candidate: 15 1 TCP 1010828543 <server_local_ipv4> 44879 typ host tcptype passive
Local ice candidate: 16 1 UDP 2013266426 <server_public_ipv4> 49033 typ host
Local ice candidate: 17 1 TCP 1015023103 <server_public_ipv4> 0 typ host tcptype active
Local ice candidate: 18 1 TCP 1010828799 <server_public_ipv4> 35449 typ host tcptype passive
Got WebRTC: ice_pwd: "36075feb87d4b9ee40b73fa92aea5c35" ice_ufrag: "4b4a2e29" dtls_fingerprint: "94:33:8B:2C:06:15:E0:C1:FE:84:3C:1F:9F:33:38:BC:FB:F1:EE:8D:33:CD:12:74:EA:06:FD:BE:40:F8:60:07"
Got ice candidate: "candidate:0 1 UDP 2122252543 <my_local_ipv4> 45674 typ host"
Got ice candidate: "candidate:1 1 TCP 2105524479 <my_local_ipv4> 9 typ host tcptype active"
```

>Does your server have more than one public IP, an active firewall, or is it behind NAT?

The server has a public IPv4 and a public IPv6 address and is behind multiple firewalls. The web server ports are open.

**Comment by Gittenburg** [comment]
Thanks, forwarding the ports solved the issue.
