### ISSUE TITLE
Current build instructions seem to be incomplete

### ISSUE THREAD

**Issue by robozman** [Johni0702/mumble-web#114]
The current build instructions are as follows:
`git clone https://github.com/johni0702/mumble-web`
`cd mumble-web`
`npm install`

In order to get the desired dist folder I had to run `npm run build` as well.
Is this intentional? If so, it would be nice to have this noted in the documentation.

Thanks

**Comment by Johni0702** [comment]
The build instructions should be correct. `npm install` should implicitly call `npm run build`.
Did you maybe run npm as root?
> Note that npm should not be ran as root, use an unprivileged user account instead.

**Comment by robozman** [comment]
Just tested this again and it looks like the issue was just a holdover before I moved away from using root. Thanks for your time.
