### ISSUE TITLE
uhm this aint suposed to happen

### ISSUE THREAD

**Issue by zaourzag** [Johni0702/mumble-web#138]
Nov 26 00:03:21 mumble systemd[1]: Started Mumble web interface.
Nov 26 00:03:21 mumble websockify[1466]: WebSocket server settings:
Nov 26 00:03:21 mumble websockify[1466]:   - Listen on localhost:64737
Nov 26 00:03:21 mumble websockify[1466]:   - Flash security policy server
Nov 26 00:03:21 mumble websockify[1466]:   - Web server. Web root: /usr/lib/node_modules/mumble-web/dist
Nov 26 00:03:21 mumble websockify[1466]:   - No SSL/TLS support (no cert file)
Nov 26 00:03:21 mumble websockify[1466]:   - proxying from localhost:64737 to mymumbleaddr:64738 (using SSL)
Nov 26 00:03:39 mumble websockify[1466]: localhost - - [26/Nov/2020 00:03:39] code 404, message File not found

also the webclient returns [1:04:17 AM] Connection error: [object Object]
which made me curious

**Comment by r4dh4l** [comment]
Hi, just found your issue in context of https://github.com/Johni0702/mumble-web/issues/147#issuecomment-800699780.

> Nov 26 00:03:21 mumble websockify[1466]: - No SSL/TLS support (no cert file)

Did you enable https / provide SSL certificates? Mumble-web needs SSL support because otherwise the web browser can not request microphone access (as far as I understood).

**Comment by zaourzag** [comment]
Not sure as this happened too long ago and I moved but I use an nginx reverse proxy

**Comment by r4dh4l** [comment]
So I think you just forgo to provide certificates. If you use "snakeoil" (see my Nginx config in https://github.com/Johni0702/mumble-web/issues/147#issuecomment-800699780 ) don't forget to `--accept-invalid-certificate` in the systemd unit (https://github.com/Johni0702/mumble-web/issues/147#issuecomment-801557186).

**Comment by zaourzag** [comment]
I'll be closing the issue now
