### ISSUE TITLE
Serving mumble-web/dist in non-webroot directory?

### ISSUE THREAD

**Issue by r4dh4l** [Johni0702/mumble-web#156]
Hi,

trying to solve https://github.com/Johni0702/mumble-web/issues/147 I have one question: Is it possible to [configure](https://github.com/Johni0702/mumble-web#configuration) mumble-web in a way that the static files of `mumble-web/dist/` are served in a non-webroot directory like `example.com/mumble-web/`?

**Comment by Johni0702** [comment]
Mumble-web does not care about its path. I've had the webrtc version running for quite a while at `https://voice.johni0702.de/webrtc/` without issues before merging it into the main version.
I believe your issue to be with your outer proxy configuration but I'm not familiar enough with nginx to tell you more. (Also, I thought you can already access the static files but the websocket connection isn't being forwarded? At least that's what it looks like from the logs as well.)

**Comment by r4dh4l** [comment]
> I believe your issue to be with your outer proxy configuration but I'm not familiar enough with nginx to tell you more. (Also, I thought you can already access the static files but the websocket connection isn't being forwarded? At least that's what it looks like from the logs as well.)

Yes. the static files could be served but after hitting "login" the logi process ends. So maybe it is time to register a domain where I can use subdomains. Using a ReverseProxy to bypass missing subdomains when using NoIP's "free dynamic DNS" service was an interesting concept but always an isolated application.
