### ISSUE TITLE
webrtc broken in Chrome Desktop 

### ISSUE THREAD

**Issue by UndeRus** [Johni0702/mumble-web#169]
Version  89.0.4389.114 

No sound from desktop browser

**Comment by sufyan-raza** [comment]
@Johni0702 same issue here. WebRTC not working properly. Connection is being made. I can send text messages but can't hear anyone. 
![mumble-web](https://user-images.githubusercontent.com/74540943/114390862-34f5b780-9bb0-11eb-9d58-c5f8b9f8d903.PNG)

**Comment by abdulwahid001** [comment]
@Johni0702 same issue while connecting to mumble-server in WebRTC mode, connection is made but with no voice whatsoever.

**Comment by UndeRus** [comment]
Also in Firefox 87.0 it works

**Comment by abdulwahid001** [comment]
@UndeRus please refer to the issue 
https://github.com/Johni0702/mumble-web/issues/136
It resolved the issue on my end

**Comment by UndeRus** [comment]
> @UndeRus please refer to the issue
> #136
> It resolved the issue on my end

I tried to expose ports and use coturn too(in my mumble-client fork is implemented usage of stun/turn servers), but same problem with establishing DTLS-SRTP connection.

**Comment by UndeRus** [comment]
After I changed coturn url to tcp mode - It began works!

**Comment by JuniorJPDJ** [comment]
@UndeRus could you do merge request with your stun/turn changes to mumble-web?
I'm also interested in this changes and it would be cool to have them in main tree.

**Comment by UndeRus** [comment]
I'll prepare pull request when have time, now you can look in this project
https://bitbucket.org/kerrigan/mumble-web-headless/

сб, 8 мая 2021 г., 0:18 JuniorJPDJ ***@***.***>:

**Comment by Jo-Blade** [comment]
@UndeRus I am trying to use you fork to use a turn server.
Can you explain me how to configure mumble-web to make it work please ??

**Comment by UndeRus** [comment]
@Jo-Blade you need to make fork of mumble-web to integrate these changes, current mumble-web doesn't support it.

**Comment by Jo-Blade** [comment]
@UndeRus yes I know but I don't know what change I need to do. If I understand good, the changes need to be done in the mulble-client library (I've tried successfuly to install mumble-web after changing the mulble-client package in package.json ton your fork on github)

**Comment by Jo-Blade** [comment]
But how can I have the exact same installation you've done in April to make it work ?
(My main goal is to enable the use of mumble-web behind a restrictive firewall using webrtc)

**Comment by UndeRus** [comment]
@Jo-Blade I had these problems in my custom project and then reproduced them in vanilla mumble-web

**Comment by Jo-Blade** [comment]
What is your custom project ? Does it work ? Can I install it ?

**Comment by Jo-Blade** [comment]
@UndeRus otherwise, What should I do to modify mumble-web to implement coturn ? (I don't know anything of webrtc...) Just update the mulble-client package or more ? Do I need some modification on mumble-web-proxy ?
