### ISSUE TITLE
How to stop and restart websockify

### ISSUE THREAD

**Issue by felix28** [Johni0702/mumble-web#19]
Hi,

I want to ask how I can stop and restart websockify using a command same as in Apache?

Thanks

**Comment by Johni0702** [comment]
This really depends on your operating system and is in no way related to mumble-web or even websockify itself.
For systemd-based distros, this page is a good resource: https://wiki.archlinux.org/index.php/Systemd#Writing_unit_files

**Comment by felix28** [comment]
Thank you for providing a good resource.

Anyways, I already did it.

For anyone who wants to stop Websockify in Linux, this is how I did it:
fuser -k [yoursocketportnumber]/tcp

To view the status if websockify is running in Linux:
fuser [yoursocketportnumber]/tcp
