### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by thejustsoul** [Johni0702/mumble-web#2]
How to use it? 

I have (fresh install): `node v6.9.4`, `npm 4.1.2`, running `Mumble server` on `port 64738` (autogenerated cert) on `Windows`

I run `npm install -g mumble-web`, then try run:
`websockify --cert="cert.pem" --key="key.pem" --ssl-only --ssl-target --web="..\node_modules\mumble-web\dist" 443 127.0.0.1:64738`
and:
`websockify --web="..\node_modules\mumble-web\dist" 8888 mumbleserver:64738`

Then open in browser https://127.0.0.1 (and http://127.0.0.1:8888), then enter name, address, port my mumble server to connection manager, and... nothing, i get error:

`[0:00:00 PM] Connecting to server 127.0.01`
`[0:00:00 PM] Connection error: [object Event]`

In Mumble server log:

`1 => <1:(-1)> New connection: 127.0.0.1:1141`
`Connection: Failed to add flow to QOS`
`1 => <1:(-1)> Connection closed: The remote host closed the connection [1]`

How to run `mumble-web` client and connect to my server? Please, step-by-step if possible.

**Comment by Johni0702** [comment]
The second command cannot work properly. Mumble requires you to use SSL.
The first command looks fine.

You probably put the address and port of the mumble server (127.0.0.1, 64738) in the connect dialog. However you need to put the address/port websockify is running on there, so in your case (with the first command) that is 127.0.0.1 with port 443.
Your browser will then connect to websockify which will in turn connect to your mumble server for you.

**Comment by thejustsoul** [comment]
I tried again:
1. `websockify --web "D:\nodejs_portable\LTS\node_modules\mumble-web\dist" --cert "D:\mycert\cert.pem" --key "D:\mycert\key.pem" 192.168.1.100:443 addressmyservermumble.tld:64738`
3. Open in browser https://192.168.1.100/, then enter in "`Connect to Server`" Address `192.168.1.100`, Port `443`, Username `test`. Press Connect... and nothing.. i see error `Connection error: [object Event]`
4. websockify crashing (after press Connect).

Maybe need another version nodejs? Or maybe need to run a websockify on Linux?
Mumble server have a valid cert. Cert and key for websockify manual generated (and here it is necessary to specify precisely the certificate that the server?) I understand it is a certificate for the site (mumble-web) and at this time, and can use a self-signed.

Log:
```
D:\nodejs_portable\LTS\work>websockify --web "D:\nodejs_portable\LTS\node_modules\mumble-web\dist" --cert "D:\mycert\cert.pem" --key "D:\mycert\key.pem" 192.168.1.100:443 addressmyservermumble.tld:64738
WebSocket settings:
    - proxying from 192.168.1.100:443 to addressmyservermumble.tld:64738
    - Web server active. Serving: D:\nodejs_portable\LTS\node_modules\mumble-web\dist
    - Running in encrypted HTTPS (wss://) mode using: D:\mycert\cert.pem, D:\mycert\key.pem
(node:4952) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
D:\nodejs_portable\LTS\node_modules\websockify\websockify.js:129
        callback(true, 'binary');
        ^

TypeError: callback is not a function
    at Object.selectProtocol [as handleProtocols] (D:\nodejs_portable\LTS\node_modules\websockify\websockify.js:129:9)
    at WebSocketServer.handleUpgrade (D:\nodejs_portable\LTS\node_modules\websockify\node_modules\ws\lib\WebSocketServer.js:171:31)
    at Server.WebSocketServer._ultron.on (D:\nodejs_portable\LTS\node_modules\websockify\node_modules\ws\lib\WebSocketServer.js:85:14)
    at emitThree (events.js:116:13)
    at Server.emit (events.js:194:7)
    at onParserExecuteCommon (_http_server.js:409:14)
    at HTTPParser.onParserExecute (_http_server.js:377:5)
```

**Comment by Johni0702** [comment]
Yes, using a self-signed cert is fine as long as your browser trusts it.

This does indeed look like something caused by websockify expecting too old of a nodejs version. You might want to try a different nodejs version for websockify or its python implementation.

**Comment by azlux** [comment]
`/usr/lib/node_modules/websockify/websockify.js:129` Same error as @thejustsoul here too

**Comment by Johni0702** [comment]
> This does indeed look like something caused by websockify expecting too old of a nodejs version. You might want to try a different nodejs version for websockify or its python implementation.

**Comment by azlux** [comment]
`nodejs -v`
`v6.10.0`
It's the last stable nodejs version, what is yours ?

**Comment by Johni0702** [comment]
I'm not using the nodejs version of websockify. I'm using the python version installed from the Debian Jessie repos:
```
root@main:~# dpkg -s websockify | grep Version
Version: 0.6.0+dfsg1-1
```

**Comment by azlux** [comment]
OK that what the problem. Can you update the readme ?

**Comment by thejustsoul** [comment]
Im stupid, help me to run this?
