### ISSUE TITLE
Does not comply with bandwidth limit set by server

### ISSUE THREAD

**Issue by florinpopescu** [Johni0702/mumble-web#22]
**Steps to reproduce:**
Speak for more than 20 seconds.

**Expected result:**
The sound is continuous and clean.

**Actual result:**
After every 4-5 seconds, there is a 200-400 ms voice interruption gap when nothing is heard.

Tested on Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by florinpopescu** [comment]
If I change in voice.js, line 49

```
      this._outbound
        .pipe(chunker(4 * 480))
        .pipe(buffer2Float32Array)
        .pipe(this._client.createVoiceStream())
```

into this:

```
      this._outbound
        .pipe(chunker(8 * 480))
        .pipe(buffer2Float32Array)
        .pipe(this._client.createVoiceStream())
```

Then the lag disappears

**Comment by florinpopescu** [comment]
The above solution does not work with Android Plumple.

**Comment by florinpopescu** [comment]
I think this something from websockify because the mumble-web is sending all the messages to the browser WebSocket (I've console.log and saw that it is ok).

Also if I increase the chunker size (.pipe(chunker(8 * 480)) or .pipe(chunker(16 * 480))), the messages sizes are increased and the transmitting frequency gets lower. So there is no gap.
If I decrease the chunker size to chunker(2 * 480) the messages sizes are decreased and the transmitting frequency gets higher. In this situation the gap appears after 1 second.

So I assume that websockify can't handle messages that are transmitted on high frequency and drops some of the messages.

**Comment by florinpopescu** [comment]
Did anyone ever encountered this?

**Comment by florinpopescu** [comment]
I saw with tcpdump that Murmur server is losing packages. So its something from Murmur.

**Comment by florinpopescu** [comment]
This does not occur with OSX version of Murmur.

**Comment by mkrautz** [comment]
Grumble doesn't implement bandwidth limiting either right now, fwiw.

**Comment by licosan** [comment]
Hi, just wondering is anyone has any more news about this ?

I had exactly the same type of behavior and could influence by tweaking with the chunk size (as described by florinpopescu), and with the (max) bandwidth parameter of the mumble server.
Best results with 16*480 and no limit server side: no real interruption, but still some sound deformation for 1sec every 5 seconds or so.
The funny thing though is that limiting the server to -say- 8K, with a large chunk makes it worse. So I'm under the impression that it is more a chunk alignment issue than a real bandwidth issue (just guessing).
