### ISSUE TITLE
add some way to hide fields in connect dialog

### ISSUE THREAD

**Issue by jmcclelland** [Johni0702/mumble-web#26]
I discovered that I could set the default port and default address in app/index.js by mucking with the ConnectDialog function.

Is there a more elegant way to do this via a configuration or setting?

Also, I commented out the token and password options in app/index.html, which would also be nice to do in a more maintainable way (perhaps via a local .css file).

**Comment by Johni0702** [comment]
You can set the default values of all fields in the connect dialog by passing them as parameters in the URL: https://voice.johni0702.de/?address=voice.johni0702.de&port=443/demo
Implemented [here](https://github.com/Johni0702/mumble-web/blob/master/app/index.js#L582-L597).

There's currently no better way to hide fields than to remove them from the html file as you did. 
I'm keeping this ticket open as a reminder for that.

**Comment by gettyhub** [comment]
It is better to change it in the config.js even though that file says to change those parameters in the config.local.js file.  
Hiding fields can also be done with true, false in config.js
