### ISSUE TITLE
was moving to channel selected, now just moves to strange channel

### ISSUE THREAD

**Issue by gettyhub** [Johni0702/mumble-web#38]
I did start out with it working correctly, but for some reason it is no longer working right.  Can't tell if this is because of websockify, apache or the murmur server.  Does it on any device I connect to it, or any other server I connect to, so something is getting jacked with my installation and not sure where to look. Possibly its' because I have too many channels?

**Comment by gettyhub** [comment]
Connecting with another client shows inconsistency between which room is selected in another client and the one it shows I'm in on mumble-web.

**Comment by gettyhub** [comment]
I can use the mumble provided client and move both users into the same room (with admin priviledges), but they do not correspond with the correct room when displayed on mumble-web.

**Comment by gettyhub** [comment]
I copied over from my original build of mumble-web over to the http root directory and it still acts the same.

**Comment by SISheogorath** [comment]
Could you please collect your findings and ideas into one big posting? Because every comment is send out by email to at least 24 people, which is kind of annoying when it happens every few minutes.

Of course we can unsubscribe, but I just ask you to be nice and a bit less spammy :) Thanks ^^
