### ISSUE TITLE
Does not work in Chrome

### ISSUE THREAD

**Issue by MartinBober** [Johni0702/mumble-web#40]
Hi,

unfortunately, voice does not seem to work in Google Chrome. I do not even get asked for permission for microphone access. Please find attached the [console log](https://github.com/Johni0702/mumble-web/files/2637374/voice.johni0702.de-1543783642366.log) from the joining your live demo.

 Problem seems to be `index.js:1147 Cannot initialize user media. Microphone will not work: {name: "NotFoundError", message: "Requested device not found", constraint: undefined, toString: ƒ}constraint: undefinedmessage: "Requested device not found"name: "NotFoundError"toString: ƒ ()__proto__: Object
`.

I'm using Chrome version 70.0.3538.110 (64 bit) on Kubuntu 18.04. Works fine with Firefox 63.0.3 (64 bit).

Thank you so much for this sharing this project. :-)

**Comment by Johni0702** [comment]
From the error message it looks like Chrome is unable to find any microphone.
Please try [this simple demo](https://webrtc.github.io/samples/src/content/getusermedia/audio/) to see if that's the issue.

**Comment by MartinBober** [comment]
It works, after I plug in a microphone in my keyboard. It seems that Chrome is a lot more picky than Firefox in regard of which audio inputs they find suitable for WebRTC.
