### ISSUE TITLE
HTML should declare decoding

### ISSUE THREAD

**Issue by Johni0702** [Johni0702/mumble-web#43]
> The character encoding of the HTML document was not declared. The document
> will render with garbled text in some browser configurations if the
> document contains characters from outside the US-ASCII range. The character
> encoding of the page must be declared in the document or in the transfer
> protocol.

Adding `<meta charset="utf-8">` should fix it, need to check back if that's the recommended way of doing it.

**Comment by streaps** [comment]
it is the recommended way.
