### ISSUE TITLE
User Join without login dialog and without join button

### ISSUE THREAD

**Issue by mickimzg** [Johni0702/mumble-web#55]
Hello, how can I pass user name and password in the URL so that the user is connected directly without getting the dialog or the join button displayed?

**Comment by Johni0702** [comment]
```
https://voice.johni0702.de/?address=voice.johni0702.de&port=443/demo&username=UserNameGoesHere&password=PasswordGoesHere
```
That'll pre-fill the fields in the connect dialog. You can also add `&joinDialog=true` to hide all of the fields and only show a single join button.
There's no way to completely remove the join dialog/button. That's a restriction of modern browsers: The user must interact with the page at least once before the page can play audio.

You can check the code for other available options: https://github.com/Johni0702/mumble-web/blob/3dda3d27feba912f5f41b44d5734b084f34a35fe/app/index.js#L877-L932
