### ISSUE TITLE
Token (channel password) is not working

### ISSUE THREAD

**Issue by Frando** [Johni0702/mumble-web#63]
Hi,
I've just setup a murmur + mumble-web installation. Everything works great, apart from one thing:

When I create a new channel (through Mumble) and assign it a password (= token), it works as it should in Mumble: Users have to add the password as an "Access token" to be able to join the channel.
However, in mumble-web even if I connect to the server with the correct "token" in the token field of the connect dialog, I cannot join the channel. The mumble-web UI just does nothing upon clicking Join, and the murmur logs state "testuser is not allowed to Enter in Testchannel" (testuser and Testchannel are the username / channel name in question).

Is this a known bug? Any recommendations on how I can further debug this?

**Comment by Johni0702** [comment]
Access token are not currently implemented.
The token field in the connect dialog was originally intended for websockify token (completely unrelated to Mumble's Access Token) but that hasn't been implemented either (and would arguably be of little use, so re-purposing it would probably a good idea).

**Comment by JPeGfr** [comment]
Hi,
we want to use mumble-web to facilitate the use of mumble in order to provide mumble as a free service for the greatest number in the event of the COVID-19 crisis. Do you think it takes a long time to add this functionality in the interface?

**Comment by yazul** [comment]
Hi,
Tokens are very usefull and after a little correction, it works fine for me !

index.js, line 347

      // TODO: token
      this.connector.connect(`wss://${host}:${port}`, {
        username: username,
        password: password,
		tokens: token.split(",") // <-- that's enough !
      }).done(client => {
        log('Connected!')

**Comment by encrypt94** [comment]
Hi,
i've made some work on this, 
If you need something pull&play it's available here:
https://github.com/encrypt94/mumble-web/tree/add-mumble-tokens

I have to do some refinements (mostly ui) then i'll make a PR to @Johni0702  in next hours/day.

**Comment by JPeGfr** [comment]
> 
> 
> Hi,
> Tokens are very usefull and after a little correction, it works fine for me !
> 
> index.js, line 347
> 
> ```
>   // TODO: token
>   this.connector.connect(`wss://${host}:${port}`, {
>     username: username,
>     password: password,
> 	tokens: token.split(",") // <-- that's enough !
>   }).done(client => {
>     log('Connected!')
> ```

Thanks a lot ! 
It's work for us to.
https://blabla.le-pic.org

It's a free french mumble-server situated near Toulouse :)

**Comment by tamielbr** [comment]
Works for me too, but just did a `npm update` and it didn't pick up a version with this change. Had to add it manually.
