### ISSUE TITLE
i18n: no locales

### ISSUE THREAD

**Issue by Mejans** [Johni0702/mumble-web#67]
Hello,
I may try to add some internationalizacion tomorrow via some JavaScript files to index.html
Would it be okay if I make a PR?

**Comment by tamielbr** [comment]
I'd be glad to make pt_BR available.

**Comment by Mejans** [comment]
Yes... I gave it

**Comment by Johni0702** [comment]
Related: #78

**Comment by Johni0702** [comment]
With above commit, there now exist the primitives to do localization and about 50% (rough estimate, might also just be 30 or 70) of strings are hooked up.
Feel free to send PRs with additional strings hooked up and/or the current ones translated.
