### ISSUE TITLE
Demo doesn't work with my server. 

### ISSUE THREAD

**Issue by BetaStacks** [Johni0702/mumble-web#7]
I am trying to use the demo with my server. Any thoughts why I would be getting a connection error?

**Comment by Johni0702** [comment]
Your websockify is probably not set up correctly (or not set up at all).
How did you start it? What does it output?

**Comment by BetaStacks** [comment]
You are probably correct. :)
I downloaded websockify onto my server but didn't start it. I thought it would automatically be running. 

Any suggestions on how I should initiate It? I am using default mumble server settings.

**Comment by Johni0702** [comment]
If you want to run it behind a reverse proxy (nginx, apache, etc.):
```websockify --ssl-target 64737 probablylocalhost:64738```
If you want websockify to do the SSLing:
```websockify --cert=mycert.crt --key=mykey.key --ssl-only --ssl-target 443 probablylocalhost:64738```

Both from https://github.com/Johni0702/mumble-web#setup

**Comment by BetaStacks** [comment]
Sorry I don't know how I spaced on that part of the docs. I had seen that too. 

This is what I get when I start up the web socket and try to connect using the demo. 

websockify --ssl-target 64737 mumbleserver:64738
WebSocket server settings:
  - Listen on :64737
  - Flash security policy server
  - No SSL/TLS support (no cert file)
  - proxying from :64737 to mumbleserver:64738 (using SSL)
xx.xx.xxx.xx: SSL connection but '/home/pi/self.pem' not found
xx.xx.xxx.xx: SSL connection but '/home/pi/self.pem' not found

**Comment by Johni0702** [comment]
If you're running websockify without an SSL certificate, you need to put a reverse proxy (like nginx, apache, etc.) before it as the webclient will always try to connect with SSL/TLS.

**Comment by BetaStacks** [comment]
Okay, I think I got the SSL working correctly. 

```
pi@201:~ $ websockify --ssl-target 64737 mumbleserver:64738WebSocket server settings:
  - Listen on :64737
  - Flash security policy server
  - SSL/TLS support
  - proxying from :64737 to mumbleserver:64738 (using SSL)
```

Now when I try to connect using the demo I get:
```
handler exception: [SSL] PEM lib (_ssl.c:2506)
handler exception: [SSL] PEM lib (_ssl.c:2506)

```

**Comment by Johni0702** [comment]
Sorry, I've never seen that error before.
I'd love to help you but all I know about websockify is from the mistakes I made with it myself. I suggest you head over to https://github.com/novnc/websockify and ask for help there.

**Comment by BetaStacks** [comment]
:) thanks for the help. I'll check that out.
