### ISSUE TITLE
Should the demo be able to connect to external servers?

### ISSUE THREAD

**Issue by booherbg** [Johni0702/mumble-web#94]
The demo seems to work for the demo settings, but when I get try an external server, I get a non-descript error in the console:

`[9:27:16 AM] Connection error: [object Object]`

Is this expected, or should the demo be able to connect externally?

Also it would be nice if the error message logging worked as expected.

**Comment by booherbg** [comment]
I see. You need `websockify` for each specific server.

**Comment by tuxayo** [comment]
Thanks, I though that was an issue the server being on another port than 443 or 80. But actually that's not an issue.
