### ISSUE TITLE
[bug ]Room listing layout indentation in firefox

### ISSUE THREAD

**Issue by Gredin67** [Johni0702/mumble-web#98]
In Firefox 68.7.0esr (64-Bit) on Windows 10 with the instance https://web.mumble.framatalk.org/ and https://mumble.april.org/
```
Protocol 1.3.0.
1.3.0~git20190125.440b173+dfsg-2
X11 Debian GNU/Linux 10 (buster)
```
I get following buggy and very anoying layout:
![MumbleWeb_Firefix](https://user-images.githubusercontent.com/35761345/80578516-da983100-8a08-11ea-802e-f3d9fbf30d34.PNG)

The rooms are not listed on a same level but with some indentation.

**Comment by Johni0702** [comment]
Hm, I can't actually reproduce this, neither with FF 75.0 (on Fedora 32) nor on FF 68.3.0esr (on an not-up-to-date Debian 10).

**Comment by Johni0702** [comment]
Ah, nvm, zooming in even once (110%) makes it happen, even on the demo server.
